### PR TITLE
Resolve issue with incorrect .pyd file extension generation

### PR DESCRIPTION
**Pull request by MrDengDengDeng**

### CODE REVIEW

**Comment by wjakob** [comment]
Related to issue #773.

**Comment by wjakob** [comment]
I am hesitant to merge this PR because there seem to be some platform-specific differences that aren't handled by this change.

On my macOS machine, the SOABI tag is `cpython-312-darwin`.  So with two dashes, rather than a dash and an underline.

**Comment by MrDengDengDeng** [comment]
> I am hesitant to merge this PR because there seem to be some platform-specific differences that aren't handled by this change.
> 
> On my macOS machine, the SOABI tag is `cpython-312-darwin`. So with two dashes, rather than a dash and an underline.
If so, you should use different rules in cmake for different platforms

**Comment by MrDengDengDeng** [comment]
If so, you should use different rules in cmake for different platforms

**Comment by wjakob** [comment]
Let me add @henryiii, who wrote this line originally. I started to look into this and became quite confused.

On my macOS laptop, the suffix is `.cpython-312-darwin.so`. On Windows, it seems to be of the form `.cp311-win_amd64.pyd`. This page presents yet another naming scheme https://peps.python.org/pep-0425/ (but is outdated), and the current version seems in disagreement  as well: https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#platform-compatibility-tags.

What are these version tags actually supposed to look like? What's the right combination of dashes and underscores to detect a compatible form and have the right mechanism for Scikit-build and PyPy?

**Comment by wjakob** [comment]
I don't know how to solve this issue on my own, and things seem stuck. It does not seem to affect many people (first time this came up). Will close for now, please reopen if you have additional information or a proposed fix.

**Pull request closed without merging**
