### PR TITLE
generalize type_caster<std::optional<T>>

### PR DESCRIPTION
**Pull request by wojdyr**
Add `optional_caster<>` that works like in pybind11.
It can be used for type casting optional types other than std::optional:
boost::optional, absl::optional, nonstd::optional, llvm::Optional, etc.

I guess these types are mostly obsolete in C++17, but there still might be a reason to use other such types. In one project I use a custom OptionalInt that has 4 bytes instead of 8 (at the cost of not using INT_MIN).

### CODE REVIEW

**Comment by wjakob** [comment]
This looks good, but how about completely separating from the STL specifics by putting the optional caster into the `detail` subfolder, just like is done for the list casters?

**Comment by wojdyr** [comment]
Makes sense, I moved it to detail/nb_optional.h, and rebased on master.

**Comment by wojdyr** [comment]
BTW, I see that type_casters for `std::nullptr_t`, `std::nullopt_t` and `std::monostate` are the same caster.
Would `none_caster` be a good name for a base struct for these three?

**Comment by wjakob** [comment]
Sure, that would be a nice simplification. Do you wish to include this in the current PR?

**Comment by wojdyr** [comment]
added

**Comment by wjakob** [comment]
Thank you!

**Pull request merged**
