### PR TITLE
Support overriding static properties defined via def_prop_ro_static.

### PR DESCRIPTION
**Pull request by hawkinsp**
See
https://github.com/pybind/pybind11/commit/e0e2ea33788e29ff5efca5842e92c6b179ca9378 for the analogous change to pybind11.

### CODE REVIEW

**Comment by wjakob** [comment]
This looks great, thank you! Could I ask you to also add a changelog entry?

**Comment by hawkinsp** [comment]
BTW, I don't suppose you have a sense for when the next release will be?

I want to land a LLVM change that depends on this one (switching the upstream MLIR Python bindings to nanobind from pybind11... because nanobind is a lot faster: https://github.com/llvm/llvm-project/pull/118583).

**Comment by wjakob** [comment]
That's awesome. Yes, I can push out a release soon.

**Comment by wjakob** [comment]
@hawkinsp I pushed a release with the accumulated changes.

**Pull request merged**
