### PR TITLE
Initial support for the Eigen library

### PR DESCRIPTION
**Pull request by wjakob**
This commit adds custom casters for the Eigen linear algebra library. It uses the existing `nb_tensor` infrastructure to implement a conversion between Eigen types and NumPy arrays that currently supports:

- `Eigen::Matrix/Array<..>` and derived types (row/column vectors)
- `Eigen::Map<..>`
- `Eigen::Ref<..>`
- Expression templates (`CwiseBinaryOp`, etc.)

There are a few limitations:

- Eigen tensors are not supported yet.
- Sparse matrix types are not supported yet.

### CODE REVIEW

**Comment by wjakob** [comment]
Could be interesting for you: @ianhbell, @brettc

**Comment by ianhbell** [comment]
I am very happy about this addition; but doesn't this cut against the explicit design goals of nanobind to be small and targeted?

**Comment by ianhbell** [comment]
Agreed; opt-in is always the way to go. I'm looking forward to playing with the Eigen support in nanobind.

**Comment by brettc** [comment]
Thanks @wjakob,  this does look interesting. I have settled on using [xtensor](https://github.com/xtensor-stack/xtensor/) for my current projects, but this gives some hints on how to integrate it.

My apologies for letting the PR stagnate. I'm still keen to push it through, but it needs more thought and my TODO keeps growing.

**Comment by wjakob** [comment]
> My apologies for letting the PR stagnate. I'm still keen to push it through, but it needs more thought and my TODO keeps growing.

Can you check with the latest version to see if it is needed? I moved the NumPy tensor exchange back onto the buffer protocol.

**Comment by brettc** [comment]
FYI: https://github.com/xtensor-stack/xtensor-python/issues/284

**Pull request merged**
